name: homie_dart
description: An implementation of the homie convention in dart.
author: EPNW <prokopwieler.hardundsoftware@gmail.com>
homepage: https://github.com/epnw/homie_dart

version: 1.0.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  meta: ^1.1.7